[package]
name = "tcp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1.6.1"
log = "0.4.22"
serde = "1.0.204"
serde_json = "1.0.120"
simple_logger = "5.0.0"
tokio = { version = "1", features = ["full"] }
